# deploy.yml

- hosts: masters
  gather_facts: yes
  connection: ssh
  vars_files:
    - vars.yml
  vars_prompt:
    - name: credential_token
      prompt: "Enter the git/registry access token should it be required. Hit enter should it not be required"
      private: true
  tasks:
    - name: Remove test namespace
      remote_user: ansible
      kubernetes.core.k8s:
        name: test
        api_version: v1
        kind: Namespace
        state: absent

    - name: Load and distributed Jetpack input
      block:
        - name: Load the CI/CD vars file from custom directory
          become: true
          ansible.builtin.include_vars:
            ignore_unknown_extensions: true
            dir: "{{ k8s_input_dir }}"

        - name: Copy K8s manifests, patches etc
          ansible.builtin.copy:
            src: "{{ k8s_input_dir }}/files"
            dest: /home/ansible
            owner: ansible
            group: ansible
            mode: '0644'
      when: k8s_input_dir is defined

- name: Integrate using maven
  ansible.builtin.import_playbook: maven_jib.yml
  when: mvn_parents is defined

- hosts: masters
  gather_facts: no
  connection: ssh
  vars_files:
    - vars.yml

  tasks:

    - name: Install PIP
      ansible.builtin.apt:
        name: pip
        state: present
      become: true

    - name: install Python pre-requisites for Kubernetes
      ansible.builtin.pip:
        name:
          - openshift
          - pyyaml
          - kubernetes

    - name: Remove jetpack namespaces
      remote_user: ansible
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        name: "{{ item.name }}"
        api_version: v1
        kind: Namespace
        state: absent
      loop:
        "{{ namespaces }}"

    - pause: seconds=10

    - name: Wait till jetpack namespaces have been deleted
      kubernetes.core.k8s_info:
        name: "{{ item.name }}"
        api_version: v1
        kind: Namespace
        wait_sleep: 1
        wait_timeout: 30
        wait_condition:
          type: Absent
      loop:
        "{{ namespaces }}"

    - name: Create k8s namespaces
      remote_user: ansible
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        name: "{{ item.name }}"
        api_version: v1
        kind: Namespace
        state: present
      loop:
        "{{ namespaces }}"

    - name: Running the kubectl pre-commands
      ansible.builtin.shell: "{{ item }}"
      loop:
        "{{ pre_k8s_cmds }}"

    - name: Create application.property configmaps
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        namespace: "{{ item.namespace }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ item.name }}-cm"
          data:
            "{{ item.application_properties }}"
      loop:
        "{{ apps }}"

    # create dummy secret for jib so deployment creation does not fail when secret is pulled lower down. It seems to be possible to do this via ServiceAccount and then that can be removed from deployment
    - name: Create K8s repository secret
      ansible.builtin.shell: "kubectl -n {{ item.namespace }} create secret docker-registry {{ item.name }}-secret --docker-server={{ registry_server_fqdn | default(git_server_fqdn) }} --docker-username={{ item.registry_account | default('dummy')}} --docker-password={{ credential_token | default ('dummy') }}"
      loop:
        "{{ apps }}"

    - name: Create deployments
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        namespace: "{{ item.namespace }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            creationTimestamp: null
            labels:
              app: "{{ item.name }}"
            name: "{{ item.name }}"
          spec:
            selector:
              matchLabels:
                app: "{{ item.name }}"
            strategy: { }
            template:
              metadata:
                creationTimestamp: null
                labels:
                  app: "{{ item.name }}"
              spec:
                containers:
                  - image: "{{ item.image | default(item.name+':'+item.namespace) }}"
                    name: "{{ item.name }}"
                    resources: { }
                    imagePullPolicy: Always
                    volumeMounts:
                      - mountPath: /config
                        name: config
                imagePullSecrets:
                  - name: "{{ item.name }}-secret"
                volumes:
                  - configMap:
                      items:
                        - key: application.properties
                          path: application.properties
                      name: "{{ item.name }}-cm"
                    name: config
          status: { }
      loop:
        "{{ apps }}"

    - name: Scale relevant deployments
      ansible.builtin.shell: "kubectl -n {{ item.namespace }} scale deployment {{ item.name }} --replicas {{ item.replicas }}"
      when: item.replicas is defined
      loop:
        "{{ apps }}"

    - name: Create services
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        namespace: "{{ item.namespace }}"
        state: present
        definition:
          apiVersion: v1
          kind: List
          items:
            - apiVersion: v1
              kind: Service
              metadata:
                creationTimestamp: null
                labels:
                  app: "{{ item.name }}"
                name: "{{ item.name }}"
              spec:
                ports:
                  - port: 80
                    protocol: TCP
                    targetPort: 8080
                selector:
                  app: "{{ item.name }}"
                type: ClusterIP
              status:
                loadBalancer: {}
      loop:
        "{{ apps }}"


    - name: Running the kubectl post-commands
      ansible.builtin.shell: "{{ item }}"
      loop:
        "{{ post_k8s_cmds }}"

    - name: Create ingress master
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        namespace: default
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: ingress-master
            annotations:
              nginx.org/mergeable-ingress-type: "master"
          spec:
            ingressClassName: nginx
            rules:
              - host: "{{ ingress.host }}"

    - name: Create ingress minions
      kubernetes.core.k8s:
        kubeconfig: /home/ansible/.kube/config
        namespace: "{{ item.namespace }}"
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: " {{ item.service_path }} "
              nginx.org/mergeable-ingress-type: "minion"
            name: "ingress-{{ item.namespace }}"
          spec:
            ingressClassName: nginx
            rules:
              - host: "{{ ingress.host }}"
                http:
                  paths:
                    - path: "{{ item.ingress_path }}"
                      pathType: Prefix
                      backend:
                        service:
                          name: "{{ item.service }}"
                          port:
                            number: 80
      loop:
        "{{ ingress.rules }}"
