# maven_jib.yml

- hosts: builder
  gather_facts: no
  connection: ssh
  vars_files:
    - vars.yml
  tasks:
    - name: Install Maven
      ansible.builtin.apt:
        name: maven
        state: present
      become: true

    # public repo
    - name: Checking out sources from a public repo
      ansible.builtin.git:
        repo: "https://{{ git_server_fqdn }}/{{ item.git_account }}/{{ item.git_repo }}.git"
        dest: "{{ item.name }}"
        version: "{{ item.git_branch }}"
      loop:
        "{{ apps }}"
      when: credential_token == "" or credential_token is not defined 

    # private repo
    - name: Checking out sources from a private repo
      ansible.builtin.include_role:
        name: github-add-deploy-key
      vars:
        key_path: ~/gh_deploy_key
        known_hosts_path: ~/.ssh/known_hosts
        key_title: ansible_key
        github_access_token: "{{ credential_token }}"
        clone_dest: "~/{{ item.name }}"
        git_account_id: "{{ item.git_account }}"
        repo: "{{ item.git_repo }}"
        branch: "{{ item.git_branch }}"
      loop:
        "{{ apps }}"
      when: credential_token is defined or credential_token != ""

    - name: Maven install
      ansible.builtin.command: "mvn install"
      args:
        chdir: "~/{{ item.name }}"
      register: mvn_out
      #      become: true
      changed_when: mvn_out.rc == 0
      when: mvn_parents is defined
      loop:
        "{{ mvn_parents }}"

    - name: Run JIB builds
      ansible.builtin.command: "mvn clean compile jib:buildTar -Dimage={{ item.name }}:{{ item.namespace }}"
      args:
        chdir: "~/{{ item.name }}/{{ item.integration_dir }}"
      register: mvn_out
      changed_when: mvn_out.rc == 0
      loop:
        "{{ apps }}"

    # https://blog.scottlowe.org/2020/01/25/manually-loading-container-images-with-containerd/
    - name: Load images from jib into containerd
      ansible.builtin.command: ctr -n=k8s.io images import jib-image.tar
      args:
        chdir: "/home/ansible/{{ item.name }}/{{ item.integration_dir }}/target"
      register: ctr_out
      become: true
      #      changed_when: '"BUILD SUCCESS" in mvn_output'
      loop:
        "{{ apps }}"

    #    - name: Print result of CTR Load
    #      ansible.builtin.debug:
    #        var: ctr_out

