# k8s_boot.yml

- name: Scan keys
  ansible.builtin.import_playbook: admin/key_scan.yml

- name: Prepare the nodes
  ansible.builtin.import_playbook: k8s_prep.yml

- name: Deploy and configure HAProxy
  ansible.builtin.import_playbook: ha_proxy.yml
  when: groups['comasters'] is defined

- name: Boot master node.
  ansible.builtin.import_playbook: k8s_master_init.yml

- name: Boot joining nodes.
  ansible.builtin.import_playbook: k8s_join_nodes.yml

- name: Copy kube config for designated users
  ansible.builtin.import_playbook: copy_kube_config.yml

- name: Install & configure IngressController and LoadBalancers.
  ansible.builtin.import_playbook: k8s_ingress_controller.yml
  when: groups['comasters'] is defined

- name: Test the cluster
  ansible.builtin.import_playbook: k8s_test_cluster.yml

- name: Print the banner
  ansible.builtin.import_playbook: print_banner.yml
