# k8s_master_init.yml

- hosts: masters
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - atomika_base

  tasks:

   - name: Initializing Kubernetes Cluster
     become: yes
     command: kubeadm init --pod-network-cidr 10.244.0.0/16 --control-plane-endpoint k8scp:6443 --upload-certs
     run_once: true

   - pause: seconds=30

   - name: Copy kube config for designated users
     ansible.builtin.include_tasks: internal/i_copy_kube_config.yml

   - name: Create Pod Network & RBAC.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items:
       kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
#        - kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
#        - curl https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml -o /home/{{ ansible_user }}/kube-flannel.yml
#        - sed -i 's/io\/v1beta1/io\/v1/' /home/{{ ansible_user }}/kube-flannel.yml
#        - kubectl apply -f /home/{{ ansible_user }}/kube-flannel.yml
#        - rm /home/{{ ansible_user }}/kube-flannel.yml

   - pause: seconds=30

...

