# k8s_master_init.yml

- hosts: masters
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - atomika_base

  vars_prompt:
    - name: "control_plane_ep"
      prompt: "Enter the DNS name of the control plane load balancer?"
      private: no
    - name: "kubectl_user"
      prompt: "Enter the name of the existing user that will execute kubectl commands?"
      private: no

  tasks:
   - name: Initializing Kubernetes Cluster
     become: yes
     #     command: kubeadm init --pod-network-cidr 10.244.0.0/16 --control-plane-endpoint "{{ ansible_eno1.ipv4.address }}:6443" --upload-certs
     command: kubeadm init --pod-network-cidr 10.244.0.0/16 --control-plane-endpoint "{{ control_plane_ep }}:6443" --upload-certs
     #command: kubeadm init --pod-network-cidr 10.244.0.0/16 --upload-certs
     run_once: true
     #delegate_to: "{{ k8s_master_ip }}"

   - pause: seconds=30

   - name: Create directory for kube config of {{ ansible_user }}.
     become: yes
     file:
       path: /home/{{ ansible_user }}/.kube
       state: directory
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: 0755

   - name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config.
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ ansible_user }}/.kube/config
       remote_src: yes
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: '0640'

   - pause: seconds=30

   - name: Remove the cache directory.
     file:
       path: /home/{{ ansible_user }}/.kube/cache
       state: absent

   - name: Create directory for kube config of {{ kubectl_user }}.
     become: yes
     file:
       path: /home/{{ kubectl_user }}/.kube
       state: directory
       owner: "{{ kubectl_user }}"
       group: "{{ kubectl_user }}"
       mode: 0755

   - name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ kubectl_user }}/.kube/config.
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ kubectl_user }}/.kube/config
       remote_src: yes
       owner: "{{ kubectl_user }}"
       group: "{{ kubectl_user }}"
       mode: '0640'

   - pause: seconds=30

   - name: Remove the cache directory.
     file:
       path: /home/{{ kubectl_user }}/.kube/cache
       state: absent

   - name: Create Pod Network & RBAC.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items:
       kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
#        - kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
#        - curl https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml -o /home/{{ ansible_user }}/kube-flannel.yml
#        - sed -i 's/io\/v1beta1/io\/v1/' /home/{{ ansible_user }}/kube-flannel.yml
#        - kubectl apply -f /home/{{ ansible_user }}/kube-flannel.yml
#        - rm /home/{{ ansible_user }}/kube-flannel.yml
          #- kubectl apply -f {{ pod_network_manifest_file }}        
          #- kubectl apply -f {{ rbac_manifest_file }}

   - pause: seconds=30

#   - name: Get the token for joining the nodes with Kuberentes master.
#     shell: kubeadm token create  --print-join-command
#     register: kubernetes_join_command
#
#   - debug:
#       msg: "{{ kubernetes_join_command.stdout }}"
#
#   - name: Copy join command to local file.
#     become: false
#     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

   - name: Configure kubectl command auto-completion.
     lineinfile:
       dest: /home/{{ ansible_user }}/.bashrc
       line: 'source <(kubectl completion bash)'
       insertafter: EOF
...

