#print_banner.yml
- hosts: localhost
  connection: local
#  vars:
#    art: |
#      ##########################################################################\n
#      #   ATOMIKA: Faster deployments to local Kubernetes   ####################\n
#      ################################  ______  ################################\n
#      ###############################  /\     \  ###############################\n
#      ##############################  /  \     \  ##############################\n
#      #############################  /    \_____\  #############################\n
#      ############################  _\    / ____/_  ############################\n
#      ###########################  /\ \  / /\     \  ###########################\n
#      ##########################  /  \ \/_/  \     \  ##########################\n
#      #########################  /    \__/    \_____\  #########################\n
#      ########################  _\    /  \    / ____/_  ########################\n
#      #######################  /\ \  /    \  / /\     \  #######################\n
#      ######################  /  \ \/_____/\/_/  \     \  ######################\n
#      #####################  /    \_____\  . /    \_____\  #####################\n
#      ####################  _\    /     / .. \    / ____/_  ####################\n
#      ###################  /\ \  /     / .... \  / /\     \  ###################\n
#      ##################  /  \ \/_____/ ...... \/_/  \     \  ##################\n
#      #################  /    \_____\ .......... /    \_____\  #################\n
#      ################  _\    /     / .......... \    / ____/_  ################\n
#      ###############  /\ \  /     / ............ \  / /\     \  ###############\n
#      ##############  /  \ \/_____/ .............. \/_/  \     \ -axiac ########\n
#      #############  /    \_____\ .................. /    \_____\  #############\n
#      #############  \    /     /_  ______  ______  _\____/ ____/_  ############\n
#      ###########  /\ \  /     /  \/\     \/\     \/\     \/\     \  ###########\n
#      ##########  /  \ \/_____/    \ \     \ \     \ \     \ \     \  ##########\n
#      #########  /    \_____\ \_____\ \_____\ \_____\ \_____\ \_____\  #########\n
#      #########  \    /     / /     / /     / /     / /     / /     /   ########\n
#      ##########  \  /     / /     / /     / /     / /     / /     /  ##########\n
#      ###########  \/_____/\/_____/\/_____/\/_____/\/_____/\/_____/  ###########\n
#      ##########################################################################\n
#      ####### MIT License, Copyright (c) 2021 S2C Consulting (PtyLtd ZA) #######\n
#      ##########################################################################
#
#  tasks:
#    - debug:
#        msg: "{{ art }}"


  vars:
    L00: "##################################################################"
    L01: "#                                                                #"
    L02: "#            ATOMIKA: Local deployments to Kubernetes            #"
    L03: "#                                                                #"
    L04: "#                     .   .xXXXX+.   .                           #"
    L05: "#                .   ..   xXXXX+.-   ..   .                      #"
    L06: "#          .   ..  ... ..xXXXX+. --.. ...  ..   .                #"
    L07: "#      .   ..  ... .....xXXXX+.  -.-..... ...  ..   .            #"
    L08: "#    .   ..  ... ......xXXXX+.  . .--...... ...  ..   .          #"
    L09: "#   .   ..  ... ......xXXXX+.    -.- -...... ...  ..   .         #"
    L10: "#  .   ..  ... ......xXXXX+.   .-+-.-.-...... ...  ..   .        #"
    L11: "#  .   ..  ... .....xXXXX+. . --xx+.-.--..... ...  ..   .        #"
    L12: "# .   ..  ... .....xXXXX+. - .-xxxx+- .-- .... ...  ..   .       #"
    L13: "#  .   ..  ... ...xXXXX+.  -.-xxxxxx+ .---... ...  ..   .        #"
    L14: "#  .   ..  ... ..xXXXX+. .---..xxxxxx+-..--.. ...  ..   .        #"
    L15: "#   .   ..  ... xXXXX+. . --....xxxxxx+  -.- ...  ..   .         #"
    L16: "#    .   ..  ..xXXXX+. . .-......xxxxxx+-. --..  ..   .          #"
    L17: "#     .   .. xXXXXXXXXXXXXXXXXXXXxxxxxx+. .-- ..   .             #"
    L18: "#         . xXXXXXXXXXXXXXXXXXXXXXxxxxxx+.  -- .                 #"
    L19: "#           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+.--                    #"
    L20: "#            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+-  Ojosh!ro           #"
    L21: "#                                                                #"
    L22: "#   MIT License, Copyright (c) 2024 S2C Consulting (PtyLtd ZA)   #"
    L23: "#                                                                #"
    L24: "##################################################################"

#  vars:
#    L00: "##########################################################################"
#    L01: "#   ATOMIKA: Faster deployments to local Kubernetes   ####################"
#    L02: "################################  ______  ################################"
#    L03: "###############################  //\\     \\ ###############################"
#    L04: "##############################  //  \\     \\  ##############################"
#    L05: "#############################  //    \\_____\\  #############################"
#    L06: "############################  _\    / ____/_  ############################"
#    L07: "###########################  /\ \  / /\     \\  ###########################"
#    L08: "##########################  /  \ \/_/  \     \\  ##########################"
#    L09: "#########################  /    \__/    \_____\\  #########################"
#    L10: "########################  _\    /  \    / ____/_  ########################"
#    L11: "#######################  /\ \  /    \  / /\     \\  #######################"
#    L12: "######################  /  \ \/_____/\/_/  \     \\  ######################"
#    L13: "#####################  /    \_____\  . /    \_____\\  #####################"
#    L14: "####################  _\    /     / .. \    / ____/_  ####################"
#    L15: "###################  /\ \  /     / .... \  / /\     \\  ###################"
#    L16: "##################  /  \ \/_____/ ...... \/_/  \     \\  ##################"
#    L17: "#################  /    \_____\ .......... /    \_____\\  #################"
#    L18: "################  _\    /     / .......... \    / ____/_  ################"
#    L19: "###############  /\ \  /     / ............ \  / /\     \\  ###############"
#    L20: "##############  /  \ \/_____/ .............. \/_/  \     \\ -axiac ########"
#    L21: "#############  /    \_____\ .................. /    \_____\\  #############"
#    L22: "#############  \    /     /_  ______  ______  _\____/ ____/_  ############"
#    L23: "###########  /\ \  /     /  \/\     \/\     \/\     \/\     \\  ###########"
#    L24: "##########  /  \ \/_____/    \ \     \ \     \ \     \ \     \\  ##########"
#    L25: "#########  /    \_____\ \_____\ \_____\ \_____\ \_____\ \_____\  #########"
#    L26: "#########  \    /     / /     / /     / /     / /     / /     /   ########"
#    L27: "##########  \  /     / /     / /     / /     / /     / /     /  ##########"
#    L28: V###########  \/_____/\/_____/\/_____/\/_____/\/_____/\/_____/  ###########"
#    L29: "##########################################################################"
#    L30: "####### MIT License, Copyright (c) 2021 S2C Consulting (PtyLtd ZA) #######"
#    L31: "##########################################################################"
  tasks:
    - debug:
        msg:
          - "{{ L00 }}"
          - "{{ L01 }}"
          - "{{ L02 }}"
          - "{{ L03 }}"
          - "{{ L04 }}"
          - "{{ L05 }}"
          - "{{ L06 }}"
          - "{{ L07 }}"
          - "{{ L08 }}"
          - "{{ L09 }}"
          - "{{ L10 }}"
          - "{{ L11 }}"
          - "{{ L12 }}"
          - "{{ L13 }}"
          - "{{ L14 }}"
          - "{{ L15 }}"
          - "{{ L16 }}"
          - "{{ L17 }}"
          - "{{ L18 }}"
          - "{{ L19 }}"
          - "{{ L20 }}"
          - "{{ L21 }}"
          - "{{ L22 }}"
          - "{{ L23 }}"
          - "{{ L24 }}"
#          - "{{ L25 }}"
#          - "{{ L26 }}"
#          - "{{ L27 }}"
#          - "{{ L28 }}"
#          - "{{ L29 }}"
#          - "{{ L30 }}"
#          - "{{ L31 }}"