#print_banner.yml
- hosts: localhost
  connection: local
  vars:
    L00: "##################################################################"
    L01: "#                                                                #"
    L02: "#            ATOMIKA: Local deployments to Kubernetes            #"
    L03: "#                                                                #"
    L04: "#                     .   .xXXXX+.   .                           #"
    L05: "#                .   ..   xXXXX+.-   ..   .                      #"
    L06: "#          .   ..  ... ..xXXXX+. --.. ...  ..   .                #"
    L07: "#      .   ..  ... .....xXXXX+.  -.-..... ...  ..   .            #"
    L08: "#    .   ..  ... ......xXXXX+.  . .--...... ...  ..   .          #"
    L09: "#   .   ..  ... ......xXXXX+.    -.- -...... ...  ..   .         #"
    L10: "#  .   ..  ... ......xXXXX+.   .-+-.-.-...... ...  ..   .        #"
    L11: "#  .   ..  ... .....xXXXX+. . --xx+.-.--..... ...  ..   .        #"
    L12: "# .   ..  ... .....xXXXX+. - .-xxxx+- .-- .... ...  ..   .       #"
    L13: "#  .   ..  ... ...xXXXX+.  -.-xxxxxx+ .---... ...  ..   .        #"
    L14: "#  .   ..  ... ..xXXXX+. .---..xxxxxx+-..--.. ...  ..   .        #"
    L15: "#   .   ..  ... xXXXX+. . --....xxxxxx+  -.- ...  ..   .         #"
    L16: "#    .   ..  ..xXXXX+. . .-......xxxxxx+-. --..  ..   .          #"
    L17: "#     .   .. xXXXXXXXXXXXXXXXXXXXxxxxxx+. .-- ..   .             #"
    L18: "#         . xXXXXXXXXXXXXXXXXXXXXXxxxxxx+.  -- .                 #"
    L19: "#           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+.--                    #"
    L20: "#            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+-  Ojosh!ro           #"
    L21: "#                                                                #"
    L22: "#   MIT License, Copyright (c) 20241 S2C Consulting (PtyLtd ZA)   #"
    L23: "#                                                                #"
    L24: "##################################################################"

  tasks:
    - debug:
        msg:
          - "{{ L00 }}"
          - "{{ L01 }}"
          - "{{ L02 }}"
          - "{{ L03 }}"
          - "{{ L04 }}"
          - "{{ L05 }}"
          - "{{ L06 }}"
          - "{{ L07 }}"
          - "{{ L08 }}"
          - "{{ L09 }}"
          - "{{ L10 }}"
          - "{{ L11 }}"
          - "{{ L12 }}"
          - "{{ L13 }}"
          - "{{ L14 }}"
          - "{{ L15 }}"
          - "{{ L16 }}"
          - "{{ L17 }}"
          - "{{ L18 }}"
          - "{{ L19 }}"
          - "{{ L20 }}"
          - "{{ L21 }}"
          - "{{ L22 }}"
          - "{{ L23 }}"
          - "{{ L24 }}"
