# key_scan.yml

- hosts: localhost
  connection: local
  tasks:
    - name: Scan keys
      block:
        - name: Create command file to scan keys of host's in inventory
          ansible.builtin.copy:
            mode: 0777
            dest: /tmp/scan_keys.sh
            content: |
              {% for host in groups['all'] %} 
                ssh-keyscan {{ hostvars[host]['ansible_host'] }} >> ~/.ssh/known_hosts 2> /tmp/scan_keys.err
              {% endfor %} 

        - name: Establish trust with all nodes by scanning keys. Errors are ignored but logged to /tmp/scan_keys.err on control node
          ignore_errors: true # might be badly configured host in inventory ==> log error to /tmp/scan_keys.err and move on
          ansible.builtin.command: sh /tmp/scan_keys.sh

      always:
        - name: Delete keyscan command file
          ansible.builtin.file:
            dest: /tmp/scan_keys.sh
            state: absent